import {test} from 'node:test';import assert from 'node:assert/strict';import {Store} from '../server/store.js';import {Controller} from '../server/control.js';
function setup(){const s=new Store(':memory:');const p={id:'p',runId:'r',faults:{},generators:[{id:'a',ratedKw:100,on:false,limitPct:50,targetLimitKw:null,availableKw:100,powerKw:0,startupRemaining:0,startupDelaySeconds:0},{id:'b',ratedKw:100,on:false,limitPct:100,targetLimitKw:null,availableKw:100,powerKw:0,startupRemaining:0,startupDelaySeconds:0}]};s.savePlant(p);const plants=new Map([['p',p],['q',{...structuredClone(p),id:'q'}]]);return {s,p,plants,c:new Controller(s,plants)};}
test('canonical global dedup, validation atomicity, priority intersections',()=>{const {s,p,c}=setup();const req={commandId:'c1',action:'set_target',targetKw:100};assert.equal(c.submit('p',req).status,'accepted');assert.equal(p.generators[0].on,false);assert.equal(c.submit('p',{targetKw:100,action:'set_target',commandId:'c1'}).duplicate,true);assert.equal(c.submit('q',req).status,'rejected');assert.equal(c.submit('p',{...req,targetKw:101}).status,'rejected');assert.equal(c.submit('p',{commandId:'low',action:'stop',priority:1,generatorId:'a'}).status,'rejected');assert.equal(c.submit('p',{commandId:'hi',action:'stop',priority:60,generatorId:'a'}).status,'accepted');assert.equal(c.list('p').find(x=>x.commandId==='c1').status,'superseded');assert.equal(p.generators[0].on,false);assert.equal(c.submit('p',{commandId:'bad',action:'set_target',targetKw:201}).status,'rejected');s.close();});
test('expiry before dispatch; sensor freeze cannot complete; restart deadline real time',()=>{let {s,p,plants,c}=setup();const t=Date.now();p.faults.offline=true;c.submit('p',{commandId:'expired',action:'start',expiresAt:new Date(t+1000).toISOString()},'REST',{now:t});c.tick(t+1001);assert.equal(c.list('p')[0].status,'expired');p.faults.offline=false;c.submit('p',{commandId:'target',action:'set_target',targetKw:100,timeoutSeconds:1},'REST',{now:t+2000});c.tick(t+2000);assert.equal(p.generators[0].targetLimitKw,50);assert.equal(p.generators[0].limitPct,100);p.generators.forEach(g=>g.powerKw=50);p.faults.sensorFreeze=true;c.tick(t+2100);assert.equal(c.list('p').find(x=>x.commandId==='target').status,'executing');c=new Controller(s,plants);c.tick(t+3000);assert.equal(c.list('p').find(x=>x.commandId==='target').status,'timed_out');assert.equal(p.generators[0].targetLimitKw,50);s.close();});
test('target checks every allocated device and signed actual error, then completion',()=>{const {s,p,c}=setup();const t=Date.now();c.submit('p',{commandId:'c',action:'set_target',targetKw:100},'REST',{now:t});c.tick(t);p.generators[0].powerKw=40;p.generators[1].powerKw=60;c.tick(t+1);assert.equal(c.list('p')[0].status,'executing');p.generators[1].powerKw=40;c.tick(t+2);assert.equal(c.list('p')[0].errorKw,-20);p.generators.forEach(g=>g.powerKw=50);c.tick(t+3);assert.equal(c.list('p')[0].status,'completed');assert.equal(c.list('p')[0].scadaSignal.adapter,'in-process-virtual-scada');s.close();});
test('stop clears pending startup and completed requires a post-dispatch model sample',()=>{const {s,p,c}=setup();p.simulationSeconds=10;p.generators.forEach(g=>{g.on=true;g.startupRemaining=10;});const t=Date.now();c.submit('p',{commandId:'stop',action:'stop'},'REST',{now:t});c.tick(t);assert.equal(p.generators[0].startupRemaining,0);c.tick(t+1);assert.equal(c.list('p')[0].status,'executing');p.simulationSeconds++;c.tick(t+2);assert.equal(c.list('p')[0].status,'completed');s.close();});
test('failed durable dispatch rolls back model, command cache and outbox together',()=>{const {s,p,c}=setup();const t=Date.now();c.submit('p',{commandId:'atomic',action:'set_target',targetKw:100},'REST',{now:t});const before=s.queueStats('p').pendingMessages;const enqueue=s.enqueue.bind(s);s.enqueue=()=>{throw Error('disk failure');};assert.throws(()=>c.tick(t),/disk failure/);assert.equal(p.generators[0].on,false);assert.equal(s.loadPlants()[0].generators[0].on,false);assert.equal(c.list('p')[0].status,'accepted');assert.equal(s.loadCommands()[0].status,'accepted');assert.equal(s.queueStats('p').pendingMessages,before);s.enqueue=enqueue;c.tick(t);assert.equal(c.list('p')[0].status,'executing');s.close();});
test('setpoint action validation applies even to known duplicate IDs',()=>{const {s,c}=setup();c.submit('p',{commandId:'stop',action:'stop'});const result=c.submit('p',{commandId:'stop',action:'stop'},'MQTT',{setpoint:true});assert.equal(result.status,'rejected');assert.equal(result.duplicate,undefined);s.close();});
test('outer model transaction rollback also restores nested command cancellation cache',()=>{const {s,c}=setup();c.submit('p',{commandId:'outer',action:'start'});assert.throws(()=>s.transaction(()=>{c.cancelPlant('p','edit');throw Error('model persistence failure');}));assert.equal(c.list('p')[0].status,'accepted');assert.equal(s.loadCommands()[0].status,'accepted');s.close();});
