import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import bind from '../scripts/media/final-deck-binding.cjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(t,fixtureNow=Date.now()){const root=fs.mkdtempSync(path.join(os.tmpdir(),'grid-deck-bind-'));t.after(()=>fs.rmSync(root,{force:true,recursive:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof v==='object'?JSON.stringify(v):v);};const hash=p=>sha(fs.readFileSync(path.join(root,p)));const now=fixtureNow;put('docs/operations/run.json',{freezeAt:new Date(now-600000).toISOString(),deadlineAt:new Date(now+60000).toISOString()});put('scripts/media/deck-template.json',fs.readFileSync('scripts/media/deck-template.json','utf8'));put('evidence.json',{});
 const deployment={appImage:'repo@sha256:'+'b'.repeat(64),sourceCommit:'a'.repeat(40),context:'charles-k3s',namespace:'gs-plai-5h',productVersion:'1.3.0',prdVersion:'reviewed'};put('docs/operations/run.json',{runId:'run',deployment,freezeAt:new Date(now-600000).toISOString(),deadlineAt:new Date(now+60000).toISOString()});const manifest={runId:'run',runtimeIdentity:{commit:'a'.repeat(40)},source:{commit:'a'.repeat(40)},productVersion:'1.3.0',deployment};put('release.json',manifest);put('video/GRID-VPP-demo-ko.mp4','synthetic video bytes');put('video/source/capture.png','synthetic capture bytes');put('video/source/vpp-command-4.json',{startedAt:new Date(now-175000).toISOString(),endedAt:new Date(now-170000).toISOString(),requestedTargetKw:125,actualKw:125,errorKw:0,lastStatus:'completed',exitCode:0,contractVersion:2,rtuId:'rtu',commandId:'command',runId:'before',events:['accepted','executing','completed'].map(status=>({status}))});put('video/source/export.json',{schemaVersion:1,contractVersion:2,productVersion:'1.3.0',plantId:'rtu',scope:'recent-command-snapshots',limit:20,commands:[{targetKw:125,actualKw:125,errorKw:0}]});
 const timeline={recordingStartedAt:new Date(now-300000).toISOString(),rehearsal:false,lead:1.7,scenes:Array.from({length:8},(_,i)=>({start:i*30,end:(i+1)*30}))};put('video/scenes.json',timeline);
 const recovery={result:'PASS',settingsMatched:true,existing:[],ownedId:'rtu',baselineRunId:'before',registration:{ownedId:'rtu',basis:'actual201',initialRunId:'before',capturedAt:new Date(now-260000).toISOString()},currentRunId:'after',checkedAt:new Date(now-5000).toISOString(),scenarioTransitions:[{scenarioId:'scenario',fromRunId:'before',toRunId:'after',preparedAt:new Date(now-110000).toISOString(),capturedAt:new Date(now-100000).toISOString()}]};put('video/source/demo-recovery.json',recovery);const video={demoRecovery:recovery,rehearsal:false,fullDecode:true,visualReview:'passed',claimsReview:'passed',releaseCommit:manifest.source.commit,manifestSha256:hash('release.json'),imageDigest:manifest.deployment.appImage,videoSha256:hash('video/GRID-VPP-demo-ko.mp4'),createdAt:new Date(now).toISOString(),duration:242,downloads:[{plantId:'rtu',scope:'recent-command-snapshots',limit:20,count:1,file:'source/export.json',sha256:hash('video/source/export.json')}]};put('video/verification.json',video);
 const facts={commandReportSha256:hash('video/source/vpp-command-4.json'),reviewed:true,productVersion:'1.3.0',prdVersion:'reviewed',videoSha256:video.videoSha256,scenesSha256:hash('video/scenes.json'),selectedRtuId:'rtu',scenarioRun:{beforeRunId:'before',afterRunId:'after',evidence:'video/source/demo-recovery.json'},externalVerification:{KMA:'unverified',AWS:'unverified',operationalVPP:'unverified'},slides:Array.from({length:14},(_,i)=>({body:'검수한 본문',notes:'실제 근거 설명',sceneIndex:i%8,sources:['evidence.json'],...(i===0||i===6?{capture:'capture.png',captureSha256:hash('video/source/capture.png')}:{})}))};put('facts.json',facts);const input={releaseManifest:'release.json',videoDir:'video',factsFile:'facts.json',outputConfig:'final.json'};return {root,put,hash,now,input,video,facts,timeline,manifest};}
test('binds real offsets, hashes, same video assets and relative reference',t=>{const f=fixture(t),c=bind(f.input,{root:f.root,now:f.now});assert.equal(c.slides.length,14);assert.equal(c.slides[0].timecode,'00:01–00:31');assert.equal(c.slides[7].timecode,'03:31–04:01');assert.equal(c.preparationTemplate,false);assert.equal(c.binding.videoSha256,f.video.videoSha256);assert.equal(c.slides[6].image,'video/source/capture.png');});
for(const mode of ['late','missing-asset','changed-video','wrong-manifest','unreviewed','placeholder','future-version','same-run'])test(`rejects ${mode}`,t=>{const f=fixture(t);if(mode==='missing-asset')fs.unlinkSync(path.join(f.root,'video/source/capture.png'));if(mode==='changed-video')f.put('video/GRID-VPP-demo-ko.mp4','different');if(mode==='wrong-manifest'){f.manifest.source.commit='c'.repeat(40);f.put('release.json',f.manifest);}if(mode==='unreviewed'){f.video.claimsReview='pending';f.put('video/verification.json',f.video);}if(mode==='placeholder'){f.facts.slides[0].body='POPULATE';f.put('facts.json',f.facts);}if(mode==='future-version'){f.manifest.productVersion='1.5.0';f.put('release.json',f.manifest);f.video.manifestSha256=f.hash('release.json');f.put('video/verification.json',f.video);f.facts.productVersion='1.5.0';f.put('facts.json',f.facts);}if(mode==='same-run'){f.facts.scenarioRun.afterRunId='before';f.put('facts.json',f.facts);}assert.throws(()=>bind(f.input,{root:f.root,now:mode==='late'?f.now+60001:f.now}));});
test('CLI refuses to overwrite existing output',t=>{const f=fixture(t);f.put('input.json',f.input);f.put('final.json','keep');const r=spawnSync(process.execPath,[path.resolve('scripts/media/prepare-final-deck.cjs'),'input.json'],{cwd:f.root,encoding:'utf8'});assert.equal(r.status,1);assert.equal(fs.readFileSync(path.join(f.root,'final.json'),'utf8'),'keep');});
for(const mode of ['invented-transition','private-symlink','parent-traversal','outside-absolute','missing-duration','nan-duration','negative-scene','utc-string','rollover-date','credential-body','wrong-run','wrong-prd','unknown-input','old-command-report','changed-recovery','output-private'])test(`security rejects ${mode}`,t=>{
 const f=fixture(t);
 if(mode==='invented-transition')f.facts.scenarioRun.afterRunId='invented';
 if(mode==='private-symlink'){f.put('artifacts/private/secret.txt','synthetic-private');fs.symlinkSync(path.join(f.root,'artifacts/private/secret.txt'),path.join(f.root,'public.txt'));f.facts.slides[0].sources=['public.txt'];}
 if(mode==='parent-traversal')f.facts.slides[0].sources=['../outside.txt'];
 if(mode==='outside-absolute')f.facts.slides[0].sources=[path.join(f.root,'evidence.json')];
 if(mode==='missing-duration')delete f.video.duration;
 if(mode==='nan-duration')f.video.duration='NaN';
 if(mode==='negative-scene'){f.timeline.scenes[0].start=-1;f.put('video/scenes.json',f.timeline);f.facts.scenesSha256=f.hash('video/scenes.json');}
 if(mode==='utc-string')f.video.createdAt=new Date(f.now).toUTCString();
 if(mode==='rollover-date')f.video.createdAt='2026-02-30T00:00:00.000Z';
 if(mode==='credential-body')f.facts.slides[0].body='Bearer synthetic-private-token';
 if(mode==='wrong-run')f.manifest.runId='other';
 if(mode==='wrong-prd')f.facts.prdVersion='wrong';
 if(mode==='unknown-input')f.input.token='not-allowed';
 if(mode==='output-private')f.input.outputConfig='artifacts/private/final.json';
 if(mode==='old-command-report'){const report=JSON.parse(fs.readFileSync(path.join(f.root,'video/source/vpp-command-4.json')));report.startedAt=new Date(f.now-500000).toISOString();f.put('video/source/vpp-command-4.json',report);f.facts.commandReportSha256=f.hash('video/source/vpp-command-4.json');}
 if(mode==='changed-recovery'){const r={...f.video.demoRecovery,currentRunId:'different'};f.put('video/source/demo-recovery.json',r);}
 f.put('release.json',f.manifest);f.video.manifestSha256=f.hash('release.json');f.put('video/verification.json',f.video);f.put('facts.json',f.facts);
 assert.throws(()=>bind(f.input,{root:f.root,now:f.now}));
 if(mode==='credential-body'){f.put('input.json',f.input);const r=spawnSync(process.execPath,[path.resolve('scripts/media/prepare-final-deck.cjs'),'input.json'],{cwd:f.root,encoding:'utf8'});assert.equal(r.status,1);assert.equal(fs.existsSync(path.join(f.root,'final.json')),false);assert.ok(!r.stderr.includes('synthetic-private-token'));}
});

test('rejects credential-like text derived from command report before config write',t=>{const f=fixture(t);const report=JSON.parse(fs.readFileSync(path.join(f.root,'video/source/vpp-command-4.json')));report.commandId='Bearer synthetic-private-fixture';f.put('video/source/vpp-command-4.json',report);f.facts.commandReportSha256=f.hash('video/source/vpp-command-4.json');f.put('facts.json',f.facts);assert.throws(()=>bind(f.input,{root:f.root,now:f.now}),/Credential/);f.put('input.json',f.input);const r=spawnSync(process.execPath,[path.resolve('scripts/media/prepare-final-deck.cjs'),'input.json'],{cwd:f.root,encoding:'utf8'});assert.equal(r.status,1);assert.equal(fs.existsSync(path.join(f.root,'final.json')),false);assert.ok(!r.stderr.includes('synthetic-private-fixture'));});

test('accepts actual unchanged authoritative microsecond UTC ledger timestamps',t=>{
 const actual=JSON.parse(fs.readFileSync('docs/operations/run.json'));const before=fs.readFileSync('docs/operations/run.json');const now=Date.parse(actual.freezeAt)+600000;const f=fixture(t,now);const run=JSON.parse(fs.readFileSync(path.join(f.root,'docs/operations/run.json')));Object.assign(run,{freezeAt:actual.freezeAt,deadlineAt:actual.deadlineAt});f.put('docs/operations/run.json',run);assert.equal(bind(f.input,{root:f.root,now}).slides.length,14);assert.deepEqual(fs.readFileSync('docs/operations/run.json'),before);assert.equal(JSON.parse(fs.readFileSync(path.join(f.root,'docs/operations/run.json'))).freezeAt,actual.freezeAt);assert.throws(()=>bind(f.input,{root:f.root,now:Date.parse(actual.freezeAt)}),/window/);assert.throws(()=>bind(f.input,{root:f.root,now:Date.parse(actual.deadlineAt)+1}),/window/);
});
for(const bad of ['2026-02-30T21:37:33.079009+00:00','2026-09-21T21:37:33.079009+09:00','Mon, 21 Sep 2026 21:37:33 GMT'])test('rejects noncanonical ledger '+bad,t=>{const f=fixture(t);const run=JSON.parse(fs.readFileSync(path.join(f.root,'docs/operations/run.json')));run.freezeAt=bad;f.put('docs/operations/run.json',run);assert.throws(()=>bind(f.input,{root:f.root,now:f.now}));});

function setFixtureVersion(f,version){const prd=version==='1.4.0'?'1.11':'reviewed';f.manifest.productVersion=version;f.manifest.deployment.productVersion=version;f.manifest.deployment.prdVersion=prd;f.put('release.json',f.manifest);const run=JSON.parse(fs.readFileSync(path.join(f.root,'docs/operations/run.json')));run.deployment={...f.manifest.deployment};f.put('docs/operations/run.json',run);f.video.manifestSha256=f.hash('release.json');const dto=JSON.parse(fs.readFileSync(path.join(f.root,'video/source/export.json')));dto.productVersion=version;f.put('video/source/export.json',dto);f.video.downloads[0].sha256=f.hash('video/source/export.json');f.put('video/verification.json',f.video);f.facts.productVersion=version;f.facts.prdVersion=prd;f.put('facts.json',f.facts);}
test('supports exactly product1.4.0/PRD1.11 with fully matching evidence',t=>{const f=fixture(t);setFixtureVersion(f,'1.4.0');const config=bind(f.input,{root:f.root,now:f.now});assert.match(config.slides[0].notes,/제품 1.4.0 \/ PRD 1.11/);assert.deepEqual(config.binding.features,{preview:true,commandExport:true});assert.ok(!JSON.stringify(config.slides).includes('입력 검증을 시연'));});
for(const version of ['1.4.1','1.4.0-rc.1','1.5.0','2.0.0'])test('rejects unreviewed matching product '+version,t=>{const f=fixture(t);setFixtureVersion(f,version);assert.throws(()=>bind(f.input,{root:f.root,now:f.now}),/Unsupported product version/);});
