import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,existsSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {backupBudget,SNAPSHOT_SOURCE} from '../scripts/remote-backup-helpers.mjs';
const script=resolve('scripts/remote-backup.mjs');
for(const expired of [false,true])test('independent actual backup CLI '+(expired?'expired original deadline launches no kubectl':'hung discovery stops within original deadline and keeps sensitive child output private'),()=>{
 const dir=mkdtempSync(join(tmpdir(),'backup-independent-'));try{mkdirSync(join(dir,'docs/operations'),{recursive:true});mkdirSync(join(dir,'bin'));const marker=join(dir,'called');writeFileSync(join(dir,'bin/kubectl'),`#!${process.execPath}\nrequire('fs').writeFileSync(${JSON.stringify(marker)},'yes');console.error('SENSITIVE_CHILD_DATABASE_BYTES');setInterval(()=>{},1000);`,{mode:0o700});
 writeFileSync(join(dir,'docs/operations/run.json'),JSON.stringify({runId:'fixture',deadlineAt:new Date(Date.now()+(expired?-1000:800)).toISOString(),deployment:{sourceCommit:'a'.repeat(40)}}));const start=Date.now();const r=spawnSync(process.execPath,[script],{cwd:dir,env:{...process.env,PATH:join(dir,'bin')+':'+process.env.PATH,REMOTE_BACKUP_PATH:'',BACKUP_SOURCE_COMMIT:'',BACKUP_METADATA_PATH:''},encoding:'utf8',timeout:4000});assert.notEqual(r.status,0);assert(Date.now()-start<3500);assert(!(r.stdout+r.stderr).includes('SENSITIVE_CHILD_DATABASE_BYTES'));assert.equal(existsSync(marker),!expired);if(!expired){const file=readdirSync(join(dir,'artifacts/operations/backups')).find(x=>x.endsWith('.json'));const j=JSON.parse(readFileSync(join(dir,'artifacts/operations/backups',file)));assert.equal(j.status,'incomplete');assert.equal(j.stage,'deployment discovery');assert.equal(j.remoteCancellationGuaranteed,false);}assert(!existsSync(join(dir,'deploy/verification')));
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('independent budget expiration blocks a second command launch',async()=>{let now=1000;const b=backupBudget({deadlineAt:new Date(1100).toISOString(),now:()=>now,maxMs:1000});await b.exec(process.execPath,['-e','process.stdout.write("ok")'],{stage:'first'});now=1100;await assert.rejects(b.exec(process.execPath,['-e','throw Error("must not launch")'],{stage:'second'}),/expired/);});
test('independent snapshot expired remote deadline creates neither final nor part',()=>{const dir=mkdtempSync(join(tmpdir(),'snapshot-deadline-'));try{const target=join(dir,'final.sqlite');const r=spawnSync(process.execPath,['--input-type=module','-e',SNAPSHOT_SOURCE,target,String(Date.now()-1)],{env:{...process.env,DB_PATH:join(dir,'absent.sqlite')},encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/deadline expired/);assert(!existsSync(target));assert(!existsSync(target+'.snapshot.part'));}finally{rmSync(dir,{recursive:true,force:true});}});
