import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../server/store.js';
import {Controller} from '../server/control.js';
import {createPlant,stepPlant} from '../server/model.js';
const now=Date.parse('2026-09-21T00:00:00Z');
function setup(path=':memory:') {const s=new Store(path),p=createPlant({name:'review control',type:'wind',count:2,ratedKw:1000,rampKwPerSec:1000,csv:'timestamp,power_kw\n2026-01-01 00:00,100\n2026-01-01 00:10,100'});s.savePlant(p);const plants=new Map([[p.id,p]]);return {s,p,plants,c:new Controller(s,plants)};}
test('expiresAt accepts explicit ISO zones/fractions and rejects permissive Date.parse calendar normalization',()=>{const {s,p,c}=setup();try{for(const value of ['1','2099-02-30T00:00:00Z','2099-13-01T00:00:00Z','2099-01-01','Jan 1 2099','2099-01-01T24:00:00Z',1,null])assert.equal(c.submit(p.id,{commandId:'bad-'+JSON.stringify(value),action:'start',expiresAt:value},'REST',{now}).status,'rejected');for(const value of ['2099-01-01T00:00:00Z','2099-01-01T09:00:00.123+09:00'])assert.equal(c.submit(p.id,{commandId:value,action:'start',expiresAt:value},'REST',{now}).status,'accepted');}finally{s.close();}});
test('expiresAt-only body change conflicts; equal priority supersedes overlapping but disjoint remains active',()=>{const {s,p,c}=setup();try{const req={commandId:'a',action:'start',generatorId:p.generators[0].id,priority:50,expiresAt:new Date(now+10000).toISOString()};c.submit(p.id,req,'REST',{now});assert.equal(c.submit(p.id,{...req,expiresAt:new Date(now+20000).toISOString()},'REST',{now}).status,'rejected');c.submit(p.id,{...req,commandId:'disjoint',generatorId:p.generators[1].id},'REST',{now});c.submit(p.id,{...req,commandId:'equal'},'REST',{now});assert.equal(c.commands.get('a').status,'superseded');assert.equal(c.commands.get('disjoint').status,'accepted');assert.equal(c.commands.get('equal').status,'accepted');}finally{s.close();}});
test('physical database reopen restores unfinished deadline; timeout retains setting until explicit stop makes power zero',()=>{const dir=mkdtempSync(join(tmpdir(),'grid-review-control-'));let f=setup(join(dir,'db.sqlite'));try{const id=f.p.id;f.c.submit(id,{commandId:'target',action:'set_target',targetKw:500,timeoutSeconds:2},'REST',{now});f.c.tick(now);const deadline=f.c.commands.get('target').deadlineAt;f.s.close();const s=new Store(join(dir,'db.sqlite')),p=s.loadPlants()[0],plants=new Map([[id,p]]);f={s,p,plants,c:new Controller(s,plants)};assert.equal(f.c.commands.get('target').deadlineAt,deadline);f.c.tick(now+2001);assert.equal(f.c.commands.get('target').status,'timed_out');assert(p.generators.every(g=>g.targetLimitKw===250&&g.on));f.c.submit(id,{commandId:'stop',action:'stop'},'REST',{now:now+2002});f.c.tick(now+2002);stepPlant(p,now+3000);f.c.tick(now+3001);assert(p.generators.every(g=>!g.on&&g.powerKw===0));assert.equal(f.c.commands.get('stop').status,'completed');}finally{f.s.close();rmSync(dir,{recursive:true,force:true});}});
