import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{DatabaseSync}from'node:sqlite';
const script=resolve('scripts/deploy-restore-rig.py'),image='127.0.0.1:15050/grid@sha256:'+'a'.repeat(64);
function fixture(){const dir=mkdtempSync(join(tmpdir(),'restore-rig-')),source=join(dir,'source.sqlite'),dest=join(dir,'lab.sqlite'),manifest=join(dir,'manifest.json');const runFile=join(dir,'run.json');writeFileSync(runFile,JSON.stringify({deadlineAt:new Date(Date.now()+60000).toISOString()}));const db=new DatabaseSync(source);db.exec('CREATE TABLE proof(value TEXT);INSERT INTO proof VALUES ("snapshot")'.replace('"snapshot"',"'snapshot'"));db.close();const sha=createHash('sha256').update(readFileSync(source)).digest('hex');const executable=join(dir,'kubectl');writeFileSync(executable,`#!/usr/bin/env python3
import sys,json,os,time
args=sys.argv[1:]
open(os.environ['FIXTURE_MANIFEST']+'.calls','a').write(json.dumps(args)+'\\n')
if os.path.exists(os.environ['FIXTURE_MANIFEST']+'.hang') and 'apply' in args:
 print('private-output-marker',flush=True);time.sleep(30)
if 'get' in args:
 print(json.dumps({'spec':{'replicas':1,'selector':{},'template':{'spec':{'containers':[{'name':'app','image':'old','env':[],'volumeMounts':[{'name':'data','mountPath':'/data'}]}],'volumes':[{'name':'data','persistentVolumeClaim':{'claimName':'grid-data'}},{'name':'mqtt-data','persistentVolumeClaim':{'claimName':'grid-mqtt-data'}}]}}}}))
elif 'apply' in args:
 open(os.environ['FIXTURE_MANIFEST'],'w').write(sys.stdin.read())
elif 'rollout' not in args: sys.exit(93)
`,{mode:0o700});return{dir,source,dest,sha,manifest,runFile,run(extra=[]){return spawnSync('python3',[script,'--run-file',runFile,'--name','grid-restore-fixture','--image',image,'--backup','snapshot.sqlite',...extra],{encoding:'utf8',timeout:15000,env:{...process.env,PATH:dir+':'+process.env.PATH,FIXTURE_MANIFEST:manifest}})},execute(){const m=JSON.parse(readFileSync(manifest)),pod=m.items.find(x=>x.kind==='Deployment').spec.template.spec,c=pod.initContainers[0].command;const code=c[3].replace("dest='/restore/lab.sqlite'",`dest=${JSON.stringify(dest)}`);return {pod,m,result:spawnSync(process.execPath,['--input-type=module','-e',code,source,c[5]],{encoding:'utf8'})};},close(){rmSync(dir,{recursive:true,force:true})}};}
test('restore manifest enforces streamed source/destination SHA before app start and retains isolated read-only source',()=>{const f=fixture();try{assert.equal(f.run(['--expected-sha256',f.sha]).status,0);const {pod,m,result}=f.execute();assert.equal(result.status,0,result.stderr);const proof=JSON.parse(result.stdout);assert.equal(proof.exactSnapshotVerified,true);assert.equal(proof.sourceSha256,f.sha);assert.equal(proof.destinationSha256,f.sha);assert.equal(proof.integrity,'ok');assert.equal(pod.volumes.find(v=>v.name==='backup-source').persistentVolumeClaim.readOnly,true);assert.equal(pod.initContainers[0].volumeMounts.find(v=>v.name==='backup-source').readOnly,true);assert.equal(pod.volumes.find(v=>v.name==='data').persistentVolumeClaim.claimName,'grid-restore-fixture-data');assert.equal(m.items.filter(x=>x.kind==='PersistentVolumeClaim').length,2);writeFileSync(f.dest,'different existing DB');const before=readFileSync(f.dest);assert.notEqual(f.execute().result.status,0);assert.deepEqual(readFileSync(f.dest),before);}finally{f.close();}});
test('wrong snapshot SHA fails before copy; optional argument keeps legacy command compatibility',()=>{const f=fixture();try{assert.equal(f.run(['--expected-sha256','0'.repeat(64)]).status,0);assert.notEqual(f.execute().result.status,0);assert.throws(()=>readFileSync(f.dest));assert.equal(f.run().status,0);const legacy=f.execute().result;assert.equal(legacy.status,0,legacy.stderr);assert.equal(JSON.parse(legacy.stdout).exactSnapshotVerified,false);assert.notEqual(f.run(['--expected-sha256','not-a-hash']).status,0);}finally{f.close();}});
test('matching hashes do not replace SQLite integrity validation',()=>{const f=fixture();try{writeFileSync(f.source,'not a sqlite database');const bad=createHash('sha256').update(readFileSync(f.source)).digest('hex');assert.equal(f.run(['--expected-sha256',bad]).status,0);const r=f.execute().result;assert.notEqual(r.status,0);assert(!r.stdout.includes('"result":"PASS"'));}finally{f.close();}});

test('hung apply is killed by remaining deadline without raw output or automatic retry',()=>{const f=fixture();try{writeFileSync(f.runFile,JSON.stringify({deadlineAt:new Date(Date.now()+3000).toISOString()}));writeFileSync(f.manifest+'.hang','');const at=Date.now(),r=f.run();assert.notEqual(r.status,0);assert(Date.now()-at<8000);assert.match(r.stderr,/timed out/);assert.match(r.stderr,/not proven cancelled/);assert.match(r.stderr,/Do not retry with a new name/);assert(!r.stderr.includes('private-output-marker'));assert(!r.stdout.includes('private-output-marker'));const calls=readFileSync(f.manifest+'.calls','utf8');assert(calls.includes('apply'));assert(!calls.includes('rollout'));}finally{f.close();}});
test('expired or missing run fails closed without even a discovery or apply',()=>{const f=fixture();try{writeFileSync(f.runFile,JSON.stringify({deadlineAt:new Date(Date.now()-1000).toISOString()}));assert.notEqual(f.run().status,0);assert(!existsSync(f.manifest+'.calls'));rmSync(f.runFile);assert.notEqual(f.run().status,0);assert(!existsSync(f.manifest+'.calls'));}finally{f.close();}});
