import test from 'node:test';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const{fixtureConfig}=createRequire(import.meta.url)('../scripts/browser-command-receipts.cjs');
test('receipt browser target rejects primary, external, credentials and mode mismatch before I/O',()=>{for(const GRID_URL of ['http://127.0.0.1:3104','http://example.invalid:3105','http://user:secret@127.0.0.1:3105','http://127.0.0.1:3109','http://127.0.0.1:3105/','http://127.0.0.1:3105?token=x'])assert.throws(()=>fixtureConfig({GRID_FIXTURE_TARGET:'isolated-restore',GRID_URL}),/URL mismatch/);assert.throws(()=>fixtureConfig({GRID_FIXTURE_TARGET:'unknown'}),/Unknown/)});
test('isolated restore requires exact approved lowercase digest, private token and approved receipt versions',()=>{const env={GRID_FIXTURE_TARGET:'isolated-restore',EXPECTED_BUNDLE_SHA256:'a'.repeat(64),API_TOKEN_FILE:'artifacts/private/deploy/api-token'};assert.equal(fixtureConfig(env).base,'http://127.0.0.1:3105');for(const hash of ['', 'A'.repeat(64),'a'.repeat(63),'sha256:'+'a'.repeat(64)])assert.throws(()=>fixtureConfig({...env,EXPECTED_BUNDLE_SHA256:hash}),/SHA256/);assert.throws(()=>fixtureConfig({...env,API_TOKEN_FILE:undefined}),/private file/);assert.throws(()=>fixtureConfig({...env,API_TOKEN_FILE:'artifacts/private/../../public-token'}),/private file/);assert.throws(()=>fixtureConfig({...env,GRID_CANDIDATE_VERSION:'1.4.0'}),/version/)});
test('default local mode remains isolated3109 with original private candidate token',()=>{const c=fixtureConfig({});assert.equal(c.base,'http://127.0.0.1:3109');assert.equal(c.tokenFile,'artifacts/private/candidate-1.5/api-token');assert.equal(c.mode,'local')});

test('approved1.6 receipt target separateslocalport/token and keepsrestore safeguards',()=>{
 const c=fixtureConfig({GRID_CANDIDATE_VERSION:'1.6.0'});assert.equal(c.base,'http://127.0.0.1:3110');assert.equal(c.tokenFile,'artifacts/private/candidate-1.6/api-token');assert.throws(()=>fixtureConfig({GRID_CANDIDATE_VERSION:'1.6.0',GRID_URL:'http://127.0.0.1:3109'}),/URL mismatch/);for(const v of ['1.6.1','1.7.1','1.8.0'])assert.throws(()=>fixtureConfig({GRID_CANDIDATE_VERSION:v}),/version/);const env={GRID_CANDIDATE_VERSION:'1.6.0',GRID_FIXTURE_TARGET:'isolated-restore',EXPECTED_BUNDLE_SHA256:'a'.repeat(64),API_TOKEN_FILE:'artifacts/private/deploy/api-token'};assert.equal(fixtureConfig(env).base,'http://127.0.0.1:3105');assert.throws(()=>fixtureConfig({...env,EXPECTED_BUNDLE_SHA256:''}),/SHA256/);
});

test('approved1.7 receipt fixture is isolated3111 and refuses prior or primary ports',()=>{
 const env={GRID_CANDIDATE_VERSION:'1.7.0'};const c=fixtureConfig(env);assert.equal(c.base,'http://127.0.0.1:3111');assert.equal(c.tokenFile,'artifacts/private/candidate-1.7/api-token');for(const GRID_URL of ['http://127.0.0.1:3110','http://127.0.0.1:3104'])assert.throws(()=>fixtureConfig({...env,GRID_URL}),/URL mismatch/);assert.equal(fixtureConfig({...env,GRID_FIXTURE_TARGET:'isolated-restore',EXPECTED_BUNDLE_SHA256:'a'.repeat(64),API_TOKEN_FILE:'artifacts/private/deploy/api-token'}).base,'http://127.0.0.1:3105');
});
