import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createRuntime} from '../server/index.js';import {createPlant,stepPlant} from '../server/model.js';
test('independent HTTP command export preserves persisted observations across old run, absent fields, auth and RTU selection without writes',async()=>{
 const r=createRuntime({dbPath:':memory:',token:'independent-export-token',env:{}}),p=createPlant({name:'private name omitted',type:'wind',count:1,ratedKw:100,rampKwPerSec:100,csv:'timestamp,power_kw\n2026-01-01 00:00,100\n2026-01-01 00:10,100'}),other=createPlant({name:'other',type:'wind',csv:'timestamp,power_kw\n2026-01-01 00:00,100\n2026-01-01 00:10,100'});
 r.plants.set(p.id,p);r.plants.set(other.id,other);r.store.savePlant(p);r.store.savePlant(other);const now=Date.now(),oldRun=p.runId;
 r.controller.submit(p.id,{commandId:'complete-observed',action:'set_target',targetKw:40},'MQTT',{now});r.controller.tick(now+1);stepPlant(p);r.controller.tick(now+2);assert.equal(r.controller.commands.get('complete-observed').status,'completed');
 p.runId=randomUUID();r.controller.submit(p.id,{commandId:'new-accepted',action:'start'},'REST',{now:now+10});r.controller.submit(p.id,{commandId:'invalid-observed',action:'invalid'},'REST',{now:now+11});r.controller.submit(other.id,{commandId:'other-rtu',action:'stop'},'REST',{now:now+12});
 const snapshot=()=>({tables:Object.fromEntries(r.store.db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(({name})=>[name,r.store.db.prepare(`SELECT * FROM ${name}`).all()])),plants:structuredClone([...r.plants]),commands:structuredClone([...r.controller.commands]),changes:r.store.db.prepare('SELECT total_changes() n').get().n});const before=snapshot();
 const server=await new Promise(resolve=>{const s=r.app.listen(0,'127.0.0.1',()=>resolve(s));});const get=(id,auth=true)=>fetch(`http://127.0.0.1:${server.address().port}/api/plants/${id}/commands/export`,{headers:auth?{Authorization:'Bearer independent-export-token'}:{}});
 try{
  for(const id of [p.id,randomUUID()]){const unauthorized=await get(id,false);assert.equal(unauthorized.status,401);assert.equal(unauthorized.headers.get('content-disposition'),null);}
  const response=await get(p.id);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const dto=await response.json();assert.equal(dto.plantId,p.id);assert.equal(dto.scope,'recent-command-snapshots');assert.equal(dto.commands.length,3);assert.deepEqual(dto.commands.map(x=>x.commandId),['invalid-observed','new-accepted','complete-observed']);
  for(const row of dto.commands){const original=r.controller.commands.get(row.commandId);assert.equal(row.status,original.status);assert.equal(row.source,original.source);for(const key of ['acceptedAt','dispatchedAt','deadlineAt','expiresAt','updatedAt'])assert.equal(row[key],original[key]??null,key);for(const key of ['actualKw','errorKw'])assert.equal(row[key],original[key]??null,key);}
  const done=dto.commands[2];assert.equal(done.runId,oldRun);assert.equal(done.targetKw,40);assert.equal(done.actualKw,40);assert.equal(done.errorKw,0);assert.equal(dto.commands[1].runId,p.runId);assert.equal(dto.commands[1].targetKw,null);assert.equal(dto.commands[0].runId,null);assert.equal(dto.commands[0].action,null);
  assert(!JSON.stringify(dto).includes(p.name));assert(!JSON.stringify(dto).includes('other-rtu'));const otherDTO=await(await get(other.id)).json();assert.deepEqual(otherDTO.commands.map(x=>x.commandId),['other-rtu']);assert.deepEqual(snapshot(),before);
 }finally{await new Promise(resolve=>server.close(resolve));await r.stop();}
});
