import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,mkdirSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import net from 'node:net';
import http from 'node:http';
import {ConnectionSupervisor,acquireLock,processIdentity} from '../scripts/connection-supervisor.mjs';
const image='127.0.0.1:15050/grid@sha256:'+'a'.repeat(64),secret='supervisor-fixture-secret-not-production',pause=ms=>new Promise(r=>setTimeout(r,ms));
async function ports(){const servers=[net.createServer(),net.createServer()];for(const s of servers)await new Promise(r=>s.listen(0,'127.0.0.1',r));const p={api:servers[0].address().port,mqtt:servers[1].address().port};for(const s of servers)await new Promise(r=>s.close(r));return p;}
async function fixture(){const dir=mkdtempSync(join(tmpdir(),'grid-supervisor-')),p=await ports(),t=Date.now();let clock=t;const run={context:'charles-k3s',namespace:'gs-plai-5h',freezeAt:new Date(t+30000).toISOString(),deadlineAt:new Date(t+60000).toISOString(),deployment:{context:'charles-k3s',namespace:'gs-plai-5h',name:'grid',appImage:image,productVersion:'1.1.0'}};const controlPath=join(dir,'control.json'),runFile=join(dir,'run.json'),tokenFile=join(dir,'token');writeFileSync(runFile,JSON.stringify(run));writeFileSync(tokenFile,secret);let control={online:true,image,ports:p,secret};const set=c=>{control={...control,...c};writeFileSync(controlPath,JSON.stringify(control));};set({});const kubectl=join(dir,'kubectl');writeFileSync(kubectl,`#!${process.execPath}
const fs=require('node:fs'),http=require('node:http'),net=require('node:net');const dir=${JSON.stringify(dir)},get=()=>JSON.parse(fs.readFileSync(dir+'/control.json'));fs.appendFileSync(dir+'/calls',JSON.stringify(process.argv.slice(2))+'\\n');const args=process.argv.slice(2),c=get();if(args.includes('get')){if(!c.online)process.exit(1);if(args.includes('deployment'))console.log(JSON.stringify({spec:{template:{spec:{containers:[{name:'app',image:c.image}]}}}}));else console.log(JSON.stringify({items:[{metadata:{uid:'fixture-pod'},status:{containerStatuses:[{name:'app',ready:true,imageID:c.image},{name:'mqtt',ready:true}]}}]}));}else if(args.includes('port-forward')){if(!c.online)process.exit(1);const api=http.createServer((req,res)=>{const c=get();res.setHeader('Content-Type','application/json');if(!c.online){res.destroy();return;}if(req.url==='/api/health')res.end(JSON.stringify({status:'ok',version:'1.1.0',mqtt:{connected:true}}));else if(req.url==='/api/config')res.end(JSON.stringify({version:'1.1.0',authRequired:true}));else if(req.url==='/api/state'&&req.headers.authorization==='Bearer '+c.secret)res.end(JSON.stringify({version:'1.1.0',plants:[],gateway:{connected:true}}));else{res.statusCode=401;res.end('{}');}}),mqtt=net.createServer(s=>s.end());api.listen(c.ports.api,'127.0.0.1');mqtt.listen(c.ports.mqtt,'127.0.0.1');api.on('error',()=>process.exit(2));mqtt.on('error',()=>process.exit(2));setInterval(()=>{if(!get().online)process.exit(1)},50);process.on('SIGTERM',()=>process.exit(0));}else process.exit(99);
`,{mode:0o700});const s=new ConnectionSupervisor({runFile,tokenFile,directory:join(dir,'state'),kubectl,ports:p,baseDelay:10,maxDelay:80,healthyDelay:10,timeout:250,now:()=>clock}).start();return{dir,p,s,run,set,clock:v=>clock=v,t,calls:()=>existsSync(join(dir,'calls'))?readFileSync(join(dir,'calls'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[],close:async()=>{await s.stop();rmSync(dir,{recursive:true,force:true});}};}
async function ready(s){for(let i=0;i<30;i++){const state=await s.tick();if(state.state==='ready')return state;await pause(50);}throw Error('fixture not ready');}

test('controlled kubectl outage retries with cap and recovers read-only with exact image/auth',async()=>{const f=await fixture();try{assert.equal((await ready(f.s)).state,'ready');assert.equal(f.s.child!==null,true);f.clock(f.t+1000);f.set({online:false});for(let i=0;i<6;i++){const r=await f.s.tick();assert.equal(r.reason,'kubernetes_unavailable');assert(r.retryInMs<=80);}assert.equal(f.s.child,null);f.set({online:true});f.clock(f.t+5000);const r=await ready(f.s);assert.equal(r.lastOutageAt,new Date(f.t+1000).toISOString());assert.equal(r.reconnectedAt,new Date(f.t+5000).toISOString());assert.equal(r.processIdentity,processIdentity(process.pid));assert.equal(r.commandsAllowed,true);const calls=f.calls();assert(calls.filter(c=>c.includes('port-forward')).length>=2);assert(calls.every(c=>c.includes('get')||c.includes('port-forward')));assert(calls.every(c=>c.includes('charles-k3s')&&c.includes('gs-plai-5h')));assert(!readFileSync(join(f.dir,'state/events.jsonl'),'utf8').includes(secret));assert(!readFileSync(join(f.dir,'state/status.json'),'utf8').includes(secret));}finally{await f.close();}});

test('wrong remote image blocks forwarding and does not replay writes',async()=>{const f=await fixture();try{f.set({image:image.replace(/a{64}$/,'b'.repeat(64))});const r=await f.s.tick();assert.equal(r.reason,'remote_image_mismatch');assert.equal(f.calls().some(c=>c.includes('port-forward')),false);assert.equal(f.s.child,null);}finally{await f.close();}});

test('occupied unrelated ports are neither killed nor replaced',async()=>{const f=await fixture(),foreign=net.createServer(s=>s.destroy());try{await new Promise(r=>foreign.listen(f.p.api,'127.0.0.1',r));const r=await f.s.tick();assert.equal(r.reason,'ports_occupied_unverified');assert(foreign.listening);assert.equal(f.calls().some(c=>c.includes('port-forward')),false);}finally{await new Promise(r=>foreign.close(r));await f.close();}});

test('existing healthy external forward survives supervisor freeze, deadline and stop',async()=>{const f=await fixture();let api,mqtt;try{api=http.createServer((q,r)=>{r.setHeader('Content-Type','application/json');if(q.url==='/api/health')r.end(JSON.stringify({status:'ok',version:'1.1.0',mqtt:{connected:true}}));else if(q.url==='/api/config')r.end(JSON.stringify({version:'1.1.0',authRequired:true}));else{assert.equal(q.headers.authorization,'Bearer '+secret);r.end(JSON.stringify({version:'1.1.0',plants:[],gateway:{connected:true}}));}});mqtt=net.createServer(s=>s.end());await new Promise(r=>api.listen(f.p.api,'127.0.0.1',r));await new Promise(r=>mqtt.listen(f.p.mqtt,'127.0.0.1',r));assert.equal((await f.s.tick()).state,'ready');assert.equal(f.s.child,null);f.clock(f.t+31000);assert.equal((await f.s.tick()).commandsAllowed,false);f.clock(f.t+60000);assert.equal((await f.s.tick()).reason,'deadline_reached');await f.s.stop();assert(api.listening&&mqtt.listening);assert.equal(f.calls().some(c=>c.includes('port-forward')),false);}finally{api?.closeAllConnections();if(api?.listening)await new Promise(r=>api.close(r));if(mqtt?.listening)await new Promise(r=>mqtt.close(r));await f.close();}});

test('singleton excludes same-process duplicate, replaces verified stale PID identity, refuses incomplete lock',()=>{const dir=mkdtempSync(join(tmpdir(),'grid-supervisor-lock-'));try{const release=acquireLock(dir);assert.throws(()=>acquireLock(dir),/already_running/);release();mkdirSync(join(dir,'supervisor.lock'));writeFileSync(join(dir,'supervisor.lock/owner.json'),JSON.stringify({pid:process.pid,identity:'reused-old-start',nonce:'old'}));acquireLock(dir)();mkdirSync(join(dir,'supervisor.lock'));assert.throws(()=>acquireLock(dir),/incomplete/);}finally{rmSync(dir,{recursive:true,force:true});}});

test('invalid startup configuration fails closed and does not spawn commands',async()=>{const f=await fixture();try{writeFileSync(f.s.runFile,'{broken');const r=await f.s.tick();assert.equal(r.reason,'invalid_run_configuration');assert.equal(f.s.closed,true);assert.equal(f.calls().length,0);}finally{await f.close();}});

test('deadline stops only owned forward; expected-image update is revalidated',async()=>{const f=await fixture();try{await ready(f.s);writeFileSync(f.s.runFile,JSON.stringify({...f.run,deployment:{...f.run.deployment,appImage:image.replace(/a{64}$/,'c'.repeat(64))}}));assert.equal((await f.s.tick()).reason,'remote_image_mismatch');assert.equal(f.s.child,null);writeFileSync(f.s.runFile,JSON.stringify(f.run));await ready(f.s);f.clock(f.t+60000);assert.equal((await f.s.tick()).state,'stopped');assert.equal(f.s.child,null);}finally{await f.close();}});
