import pathlib,subprocess as s,json,sys,urllib.request,hashlib,re,datetime
name,prefix,version,source=sys.argv[1:];p=pathlib.Path('deploy/verification/final-restore-20260921');baselineDir=pathlib.Path('deploy/verification/candidate-'+source);expected=json.load(open(baselineDir/'provenance.json'))['imageManifest'];image='127.0.0.1:15050/grid@'+expected;k=['kubectl','--context','charles-k3s','-n','gs-plai-5h'];d=json.loads(s.check_output(k+['get','pods','-l','app='+name,'-o','json'],timeout=15));assert len(d['items'])==1;pod=d['items'][0];assert all(c['ready']for c in pod['status']['containerStatuses']);assert next(c for c in pod['status']['containerStatuses']if c['name']=='app')['imageID']==image;(p/(prefix+'-pod.json')).write_text(json.dumps(d,indent=2)+'\n');x=json.loads(s.check_output(k+['logs',pod['metadata']['name'],'-c','restore-database'],timeout=15));assert x['exactSnapshotVerified']and not x['existingDestination'];assert x['sourceSha256']==x['destinationSha256']==json.load(open('deploy/verification/final-backup-20260921.json'))['sha256'];(p/(prefix+'-init.json')).write_text(json.dumps(x,indent=2)+'\n')
token=pathlib.Path('artifacts/private/deploy/api-token').read_text().strip()
def api(path):return json.load(urllib.request.urlopen(urllib.request.Request('http://127.0.0.1:3105'+path,headers={'Authorization':'Bearer '+token}),timeout=15))
state=api('/api/state');assert state['version']==version;b=json.load(open('deploy/verification/candidate-d98d3c4/pre-upgrade/baseline.json'))
def project(a,t):
 if isinstance(t,dict):return{k:project(a[k],v)for k,v in t.items()}
 if isinstance(t,list)and t and isinstance(t[0],dict)and'id'in t[0]:
  assert len(a)==len(t);actualIds=[x['id']for x in a];expectedIds=[x['id']for x in t];assert len(set(actualIds))==len(actualIds)and len(set(expectedIds))==len(expectedIds);assert set(actualIds)==set(expectedIds)
  return[project(next(x for x in a if x['id']==v['id']),v)for v in t]
 return a
assert len(state['plants'])==5;plants=project(state['plants'],b['plants']);assert plants==b['plants'];scenes=api('/api/scenarios');assert len(scenes)==len(b['scenarios']);assert project(scenes,b['scenarios'])==b['scenarios'];(p/(prefix+'-canonical-data.json')).write_text(json.dumps({'result':'PASS','checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'version':version,'beforeFixtureMutation':True,'plants':plants,'scenarios':b['scenarios'],'baseline':'deploy/verification/candidate-d98d3c4/pre-upgrade/baseline.json','canonicalGeneratorOnLimitPctIncluded':True},indent=2)+'\n')
index=urllib.request.urlopen('http://127.0.0.1:3105',timeout=15).read();original=json.load(open(baselineDir/'served-assets.json'));assert hashlib.sha256(index).hexdigest()==original['indexSha256'];assets=[]
for path in re.findall(r'(?:src|href)="(/assets/[^\"]+)"',index.decode()):
 data=urllib.request.urlopen('http://127.0.0.1:3105'+path,timeout=15).read();sha=hashlib.sha256(data).hexdigest();assert sha==next(x['sha256']for x in original['assets']if x['path']==path);assets.append({'path':path,'sha256':sha})
(p/(prefix+'-served-assets.json')).write_text(json.dumps({'result':'PASS','version':version,'image':image,'runtimeSourceCommit':json.load(open(baselineDir/'provenance.json'))['sourceCommit'],'indexSha256':original['indexSha256'],'assets':assets,'harnessSourceDistinctFromCompiledRuntime':True},indent=2)+'\n');print(json.dumps({'result':'PASS','pod':pod['metadata']['name'],'uid':pod['metadata']['uid'],'image':image}))
