FROM eclipse-mosquitto:2@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
USER root
RUN apk upgrade --no-cache
ARG SOURCE_COMMIT=uncommitted
LABEL org.opencontainers.image.revision=$SOURCE_COMMIT
USER 1000:1000
