import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
const verifier=resolve('scripts/verify-delivery.mjs');const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(){const root=mkdtempSync(join(tmpdir(),'delivery-inventory-review-'));const put=(p,b)=>{mkdirSync(dirname(join(root,p)),{recursive:true});writeFileSync(join(root,p),b);};const json=(p,v)=>put(p,JSON.stringify(v));const read=p=>JSON.parse(readFileSync(join(root,p)));const sha=p=>hash(readFileSync(join(root,p)));const image='repo/app@sha256:'+'a'.repeat(64),commit='b'.repeat(40),stamp='2026-09-21T21:45:00Z';
 for(const p of ['README.md','docs/GOAL-VPP-AUTONOMOUS.md','docs/PRD-VPP-SCADA-RTU.md','docs/product/PRD-CHANGELOG.md','docs/product/IDEAS.md','docs/product/acceptance.json','docs/protocol.md','scripts/vpp-client.js','scripts/client-message.js','deploy/README.md','deploy/app.yaml','docs/security/VULNERABILITY-MANAGEMENT.md','docs/issues/ISSUES.md','docs/operations/DELIVERY-PLAN.md'])put(p,'fixture');
 json('docs/operations/run.json',{runId:'test',freezeAt:'2026-09-21T21:37:33Z',deadlineAt:'2026-09-21T22:07:33Z',deployment:{appImage:image,sourceCommit:commit}});put('backup','synthetic db bytes');
 json('manifest.json',{runId:'test',productVersion:'1.2.0',source:{commit},runtimeIdentity:{commit},deployment:{appImage:image},backup:{localPath:'backup',sha256:sha('backup')}});
 const manifestHash=sha('manifest.json');const videoDir='artifacts/video',deckDir='artifacts/presentation';
 for(const p of ['GRID-VPP-demo-ko.mp4','GRID-VPP-demo-ko.srt','narration-ko.md','scenes.json','source/recording-config.original.json','source/release-binding-proof.json'])put(videoDir+'/'+p,'fixture');
 json(videoDir+'/source/recording-config.original.json',{scenes:[]});json(videoDir+'/source/release-binding-proof.json',{result:'PASS',remoteImageMatched:true});
 json(videoDir+'/source/release-manifest.json',read('manifest.json'));const videoHash=sha(videoDir+'/GRID-VPP-demo-ko.mp4');const video={rehearsal:false,fullDecode:true,visualReview:'passed',claimsReview:'passed',releaseCommit:commit,manifestSha256:manifestHash,imageDigest:image,videoSha256:videoHash,createdAt:stamp,dimensions:'1920x1080',codecs:'H264/AAC',audioMeanDb:-20,duration:10,frames:[]};
 for(let i=1;i<=3;i++){const p=videoDir+'/frame-'+i+'.png';put(p,'frame');video.frames.push(p);}json(videoDir+'/verification.json',video);
 for(const p of ['GRID-VPP-presentation-ko.pptx','speaker-notes.md','source/build-deck.mjs','source/media-deadline.cjs','source/REGENERATE.md'])put(deckDir+'/'+p,'fixture');
 json(deckDir+'/source/config.original.json',{videoRelativePath:'../video/GRID-VPP-demo-ko.mp4'});json(deckDir+'/source/config.portable.json',{});json(deckDir+'/source/video-verification.json',video);json(deckDir+'/source/release-manifest.json',read('manifest.json'));json(deckDir+'/docs/operations/run.json',read('docs/operations/run.json'));
 json(deckDir+'/validation.json',{finalSha256:sha(deckDir+'/GRID-VPP-presentation-ko.pptx'),packageIntegrity:{status:'pass'},presentationLayout:{exitCode:0,findingCount:0},fontSelection:{passed:true},firstPartyImport:{passed:true,sha256:sha(deckDir+'/GRID-VPP-presentation-ko.pptx')}});for(let i=1;i<=12;i++)put(deckDir+'/slide-'+String(i).padStart(2,'0')+'.png','slide');
 json(deckDir+'/verification.json',{rehearsal:false,renderedEverySlide:true,editableTextAndArchitecture:true,visualReview:'passed',claimsReview:'passed',releaseCommit:commit,manifestSha256:manifestHash,videoSha256:videoHash,createdAt:'2026-09-21T21:50:00Z',slideCount:12});
 const code=['scripts/media/media-deadline.cjs','scripts/media/record-demo.cjs','scripts/media/recording-sources.cjs','scripts/media/release-binding.cjs','scripts/media/release-features.cjs','scripts/media/validate-command-download.cjs','scripts/media/scene-plan.cjs','scripts/media/prepare-final-scenes.cjs','scripts/verify-release.mjs','scripts/pod-identity.mjs','scripts/vpp-client.js','scripts/client-message.js','package.json','package-lock.json'];for(const p of code)put(videoDir+'/source/code/'+p,'source');
 const list=(base,paths)=>paths.map(path=>({path,sha256:sha(base+'/'+path)}));
 json(videoDir+'/source/reproduction.json',{schemaVersion:1,recordingConfig:'source/recording-config.original.json',recordingConfigSha256:sha(videoDir+'/source/recording-config.original.json'),files:list(videoDir,code.map(p=>'source/code/'+p))});
 const deckFiles=['source/config.original.json','source/config.portable.json','source/build-deck.mjs','source/media-deadline.cjs','source/release-manifest.json','source/video-verification.json','docs/operations/run.json','validation.json'];json(deckDir+'/reproduction-manifest.json',{schemaVersion:1,exactConfigSha256:sha(deckDir+'/source/config.original.json'),files:list(deckDir,deckFiles)});
 return {root,put,json,read,sha,videoDir,deckDir};}
function execute(f){const r=spawnSync(process.execPath,[verifier,'--manifest','manifest.json'],{cwd:f.root,encoding:'utf8'});return {status:r.status,output:r.stdout+r.stderr};}
test('independent delivery fixture proves only artifact consistency, never completion',()=>{const f=fixture();try{const r=execute(f);assert.equal(r.status,0,r.output);const result=JSON.parse(r.output);assert.equal(result.completionClaim,false);assert.equal(result.result,'ARTIFACT_CHECKS_PASSED');}finally{rmSync(f.root,{recursive:true,force:true});}});
for(const [name,change]of [
 ['changed source manifest',f=>f.json(f.videoDir+'/source/release-manifest.json',{different:true})],
 ['failed package validation',f=>{const r=f.read(f.deckDir+'/validation.json');r.packageIntegrity.status='fail';f.json(f.deckDir+'/validation.json',r);}],
 ['same release different reviewed video',f=>{f.put(f.videoDir+'/GRID-VPP-demo-ko.mp4','different-video');const v=f.read(f.videoDir+'/verification.json');v.videoSha256=f.sha(f.videoDir+'/GRID-VPP-demo-ko.mp4');f.json(f.videoDir+'/verification.json',v);}],
 ['missing deadline source',f=>{const r=f.read(f.videoDir+'/source/reproduction.json');r.files=r.files.filter(x=>!x.path.endsWith('/media-deadline.cjs'));f.json(f.videoDir+'/source/reproduction.json',r);}],
 ['empty reproduction list',f=>{const r=f.read(f.videoDir+'/source/reproduction.json');r.files=[];f.json(f.videoDir+'/source/reproduction.json',r);}],
 ['wrong config hash',f=>{const r=f.read(f.deckDir+'/reproduction-manifest.json');r.exactConfigSha256='0'.repeat(64);f.json(f.deckDir+'/reproduction-manifest.json',r);}],
 ['both image digests invalid',f=>{const m=f.read('manifest.json');m.deployment.appImage='not-a-digest';f.json('manifest.json',m);const run=f.read('docs/operations/run.json');run.deployment.appImage=m.deployment.appImage;f.json('docs/operations/run.json',run);for(const p of [f.videoDir+'/verification.json',f.deckDir+'/verification.json']){const v=f.read(p);v.manifestSha256=f.sha('manifest.json');v.imageDigest='also-invalid';f.json(p,v);}}]
])test('independent delivery rejects '+name,()=>{const f=fixture();try{change(f);const r=execute(f);assert.notEqual(r.status,0,r.output);assert.match(r.output,/INCOMPLETE/);const expected={'changed source manifest':'Video source manifest is the selected release','failed package validation':'PPT package, layout, font and reimport checks passed','same release different reviewed video':'Deck was made from this exact reviewed video','missing deadline source':'All required recorder sources are inventoried','empty reproduction list':'Reproduction inventory is nonempty: source/reproduction.json','wrong config hash':'Exact deck configuration hash','both image digests invalid':'Release has a valid immutable image digest'}[name];assert(JSON.parse(r.output).failures.includes(expected),r.output);}finally{rmSync(f.root,{recursive:true,force:true});}});
