import {DatabaseSync,backup} from 'node:sqlite';
import {resolve} from 'node:path';
import {existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
const source=resolve(process.argv[2]||process.env.DB_PATH||'data/lab.sqlite');
const destination=process.argv[3];
if(!destination||!existsSync(source))throw Error('Usage: node scripts/backup.js EXISTING_DB NEW_BACKUP_PATH');
if(existsSync(destination))throw Error('Refusing to overwrite existing backup');
mkdirSync(dirname(resolve(destination)),{recursive:true});
const db=new DatabaseSync(source,{readOnly:true});
writeFileSync(destination,'',{flag:'wx',mode:0o600});
await backup(db,destination);db.close();
const check=new DatabaseSync(destination,{readOnly:true});
if(check.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Backup integrity check failed');
check.close();console.log(`Consistent SQLite backup: ${destination}`);
