import pathlib,json,hashlib,datetime,shutil
p=pathlib.Path('artifacts/checkpoints/reconnect-20260921T1325')
load=lambda f:json.loads((p/f).read_text())
lines=lambda f:[json.loads(x) for x in (p/f).read_text().splitlines()]
pod=load('pod-raw.json')['items'][0];meta={'name':pod['metadata']['name'],'uid':pod['metadata']['uid'],'containers':[{k:c[k] for k in ['name','ready','restartCount','imageID']} for c in pod['status']['containerStatuses']]};(p/'pod.json').write_text(json.dumps(meta,indent=2)+'\n');(p/'pod-raw.json').unlink()
a=lines('audit-observations.jsonl');primary=lines('primary-observations.jsonl');rows=load('persisted-outbox.json');out=[]
for b,n in zip(a,a[1:]):
 for old,new in zip(b['rtus'],n['rtus']):
  if new['sampleDiscontinuities']<=old['sampleDiscontinuities']:continue
  delta=new['samples']-old['samples'];start=old['lastSimulationSeconds']+1;end=new['lastSimulationSeconds']-delta
  found=[r for r in rows if r['plant']==old['rtuId'] and any(start<=v<=end for v in r['simulationSeconds'])]
  window=[s for r in rows if r['plant']==old['rtuId'] for s in r['simulationSeconds']];window.sort()
  out.append({'rtuId':old['rtuId'],'beforeAt':b['checkedAt'],'afterAt':n['checkedAt'],'beforeSequence':old['highestSequence'],'afterSequence':new['highestSequence'],'observedSampleDelta':delta,'inferredMissingSampleRange':[start,end],'persistedMissingSamples':sum(sum(start<=v<=end for v in r['simulationSeconds']) for r in found),'missedObservedSequences':[r['seq'] for r in found],'createdAt':[r['created'] for r in found],'ackedAt':[r['acked'] for r in found],'allPubackRecorded':all(r['acked'] for r in found),'windowSamples':len(window),'windowContinuous':all(y==x+1 for x,y in zip(window,window[1:]))})
base=next(x for x in a if x['checkedAt']>'2026-09-21T13:24:20');pb=next(x for x in primary if x['checkedAt']>'2026-09-21T13:24:20')
summary={'capturedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'range':['2026-09-21T13:23:30Z','2026-09-21T13:27:30Z'],'spontaneousBaselineAfter':'2026-09-21T13:24:20Z','plannedHandoff':'13:23:07–13:23:13 and settling prefix through13:24:20 excluded from spontaneous counter deltas','pod':meta,'supervisorEvents':lines('supervisor-events.jsonl'),'counterDelta':{'primaryApiErrors':[pb['apiErrors'],primary[-1]['apiErrors']],'primaryConnectionErrors':[pb['connectionErrors'],primary[-1]['connectionErrors']],'auditConnectionErrors':[base['connectionErrors'],a[-1]['connectionErrors']]},'findings':{'rows':len(rows),'samples':sum(r['count'] for r in rows),'allWindowPubackRecorded':all(r['acked'] for r in rows),'missingObservedBatches':sum(len(r['missedObservedSequences']) for r in out),'missingObservedSamplesPersisted':sum(r['persistedMissingSamples'] for r in out),'rootCause':'Unknown. health timeout after5004ms is local probe symptom, not remote root cause.','timing':'Use exact persisted timestamps below; do not equate missed publication time with logged disconnect. Remote/local historical clock synchronization not independently established.','limits':'Cumulative observation reconstruction, no raw subscriber payload/packet/broker subscriber trace. Publisher PUBACK does not prove subscriber receipt. No universal zero-loss claim.','localObservationCadence':{'auditGapFrom':'2026-09-21T13:24:36.624Z','auditGapTo':'2026-09-21T13:25:52.042Z','gapMs':75418,'meaning':'Snapshot cadence pause observed locally; cause unknown, not proof of host sleep or server stall.'}},'rtus':out,'sourceScope':'Remote app exact3fa3ba0 and broker digests in pod metadata; store/transport semantics and clean-session defaults from immutable1303 evidence. Supervisor source copy is currentc7bcf4b, not independent process-memory attestation.','query':'One bounded read-only SQLite SELECT without ORDER BY; remote output metadata only. No database settings, application, observer or tunnel changes.'}
(p/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
for name in ['telemetry-audit.mjs','telemetry-audit-monitor.mjs']:
 shutil.copyfile(pathlib.Path('artifacts/soak/telemetry-audit/2026-09-21T12-22-05-577Z-9a9f5e31/source')/name,p/'source'/name)
print(json.dumps({'deltas':summary['counterDelta'],'batches':summary['findings']['missingObservedBatches'],'samples':summary['findings']['missingObservedSamplesPersisted'],'rows':len(rows),'details':out},indent=2))
