import mqtt from 'mqtt';
import {readFileSync} from 'node:fs';
import {initialMetrics,publicMetrics} from './metrics.js';
export function connectionOptions(clientId,env=process.env){const o={clientId,clean:true,reconnectPeriod:1500,connectTimeout:10000,rejectUnauthorized:true};if(env.MQTT_USERNAME)o.username=env.MQTT_USERNAME;if(env.MQTT_PASSWORD)o.password=env.MQTT_PASSWORD;for(const [key,name] of [['MQTT_CA','ca'],['MQTT_CERT','cert'],['MQTT_KEY','key']])if(env[key])o[name]=readFileSync(env[key]);return o;}
export class Transport {
 constructor(store,controller,plants,{url=process.env.MQTT_URL||'mqtt://127.0.0.1:1883',prefix=process.env.MQTT_PREFIX||'vpp',telemetrySeconds=Number(process.env.TELEMETRY_SECONDS||60),env=process.env,connect=mqtt.connect}={}){
  if(!prefix||/[+#\u0000]/.test(prefix)||prefix.endsWith('/'))throw Error('Invalid MQTT prefix');if(!Number.isFinite(telemetrySeconds)||telemetrySeconds<=0)throw Error('Invalid telemetry period');
  this.store=store;this.controller=controller;this.plants=plants;this.url=url;this.prefix=prefix;this.telemetrySeconds=telemetrySeconds;this.env=env;this.connect=connect;this.devices=new Map();this.running=false;this.gatewayClient=null;this.gatewayError=null;this.deviceConfig=env.MQTT_DEVICE_CONFIG?JSON.parse(readFileSync(env.MQTT_DEVICE_CONFIG,'utf8')):{};
 }
 guard(d,fn){try{return fn();}catch{if(d){if(d.inflight){clearTimeout(d.inflight.delay);clearTimeout(d.inflight.timeout);d.inflight=null;}d.metrics.telemetryPending=0;d.metrics.lastError='Transport operation failed; queued data retained';d.retryAt=Date.now()+1000;}else this.gatewayError='Transport operation failed';try{this.store.audit('error','Transport operation failed; inspect storage and connection health');}catch{ /* Storage failure must not crash the event loop. */ }return undefined;}}
 topic(id,suffix){return `${this.prefix}/rtu/${id}/${suffix}`;}
 options(id){const base=this.env.MQTT_CLIENT_ID||'vpp-scada-lab';const env={...this.env,MQTT_CLIENT_ID:id?`${base}-${id}`:base,...(id?this.deviceConfig[id]:{})};return connectionOptions(env.MQTT_CLIENT_ID,env);}
 start(){if(this.running)return;this.running=true;const topic=`${this.prefix}/gateway/status`;this.gatewayClient=this.connect(this.url,{...this.options(),will:{topic,payload:JSON.stringify({online:false}),qos:1,retain:true}});this.gatewayClient.on('connect',()=>this.guard(null,()=>{this.gatewayError=null;this.gatewayClient.publish(topic,JSON.stringify({online:true,timestamp:new Date().toISOString()}),{qos:1,retain:true});}));this.gatewayClient.on('error',()=>{this.gatewayError='Gateway MQTT connection error';});this.sync();this.pumpTimer=setInterval(()=>this.guard(null,()=>this.pump()),100);this.batchTimer=setInterval(()=>{for(const id of this.plants.keys())try{this.store.batch(id);}catch{this.guard(null,()=>{throw Error('Batch failure');});}},this.telemetrySeconds*1000);}
 sync(){for(const [id,p] of this.plants){let d=this.devices.get(id);if(!d){d={id,client:null,metrics:initialMetrics(this.store.loadMetrics(id)),inflight:null,retryAt:0};this.devices.set(id,d);}if(p.faults.offline){if(d.client){const c=d.client;d.client=null;if(d.inflight){clearTimeout(d.inflight.delay);clearTimeout(d.inflight.timeout);if(d.metrics.telemetryPending)d.metrics.telemetryFailed++;d.inflight=null;}d.metrics.telemetryPending=0;this.save(d);c.end(true);}continue;}if(!d.client&&this.running)this.open(d);}}
 open(d){const topic=this.topic(d.id,'status');const client=this.connect(this.url,{...this.options(d.id),will:{topic,payload:JSON.stringify({rtuId:d.id,online:false}),qos:1,retain:true}});d.client=client;client.on('connect',()=>this.guard(d,()=>{d.metrics.lastError=null;client.subscribe([this.topic(d.id,'command'),this.topic(d.id,'setpoint')],{qos:1},e=>this.guard(d,()=>{if(e)d.metrics.lastError='Control subscription failed';else client.publish(topic,JSON.stringify({rtuId:d.id,online:true,timestamp:new Date().toISOString()}),{qos:1,retain:true});}));}));client.on('error',()=>this.guard(d,()=>{d.metrics.lastError='RTU MQTT connection error';this.save(d);}));client.on('message',(topic,payload,packet)=>this.guard(d,()=>{const started=Date.now();let request;try{if(payload.length>8192)throw Error('Control payload exceeds 8192 bytes');request=JSON.parse(payload.toString());}catch(e){request={commandId:null,action:null};}const result=this.controller.submit(d.id,request,'MQTT',{retained:packet.retain,setpoint:topic.endsWith('/setpoint')});this.recordCommand(result,started);}));}
 recordCommand(result,started=Date.now()){let d=this.devices.get(result.plantId);if(!d){d={id:result.plantId,client:null,metrics:initialMetrics(this.store.loadMetrics(result.plantId)),inflight:null,retryAt:0};this.devices.set(result.plantId,d);}d.metrics.commandsReceived++;if(result.duplicate)d.metrics.commandsDuplicate++;else if(result.status==='accepted')d.metrics.commandsAccepted++;else d.metrics.commandsRejected++;d.metrics.lastCommandMs=Date.now()-started;d.metrics.recentCommands.unshift({commandId:result.commandId,status:result.status,source:result.source,duplicate:!!result.duplicate,timestamp:new Date().toISOString()});d.metrics.recentCommands=d.metrics.recentCommands.slice(0,20);this.save(d);}
 save(d){this.store.saveMetrics(d.id,d.metrics);}
 collected(id,frame){let d=this.devices.get(id);if(!d){d={id,client:null,metrics:initialMetrics(this.store.loadMetrics(id)),inflight:null,retryAt:0};this.devices.set(id,d);}const m=d.metrics;m.generatedSamples++;m.firstSampleAt??=frame.timestamp;m.lastSampleAt=frame.timestamp;this.save(d);}
 pump(){this.sync();for(const [id,d] of this.devices)this.guard(d,()=>{const p=this.plants.get(id);if(!p||!d.client?.connected||d.inflight||Date.now()<d.retryAt)return;const row=this.store.pending(id);if(!row)return;const token={id:row.id};d.inflight=token;const telemetry=row.topic==='telemetry';if(telemetry){d.metrics.telemetryAttempts++;d.metrics.telemetryPending=1;}this.store.attempt(row.id);this.save(d);const finish=(error,started)=>this.guard(d,()=>{if(d.inflight!==token)return;clearTimeout(token.timeout);d.inflight=null;d.metrics.telemetryPending=0;if(error){if(telemetry)d.metrics.telemetryFailed++;d.metrics.lastError=error;d.retryAt=Date.now()+1000;}else{this.store.ack(row.id);if(telemetry){d.metrics.telemetryConfirmed++;d.metrics.confirmedBytes+=Buffer.byteLength(row.body);d.metrics.lastConfirmedAt=new Date().toISOString();d.metrics.lastPubackMs=Date.now()-started;d.metrics.lastPayloadBytes=Buffer.byteLength(row.body);d.metrics.lastBatchSamples=JSON.parse(row.body).sampleCount;}d.metrics.lastError=null;}this.save(d);});token.delay=setTimeout(()=>this.guard(d,()=>{if(d.inflight!==token||!this.running)return;const current=this.plants.get(id);if(!current||!d.client?.connected||current.faults.offline){finish('Disconnected before publish');return;}let x=current.faultRngState>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;current.faultRngState=x>>>0;this.store.savePlant(current);if((current.faults.dropPct||0)>((x>>>0)/4294967296)*100){finish('Injected publish failure');return;}const started=Date.now();token.timeout=setTimeout(()=>{finish('PUBACK timeout');if(d.client){const c=d.client;d.client=null;c.end(true);}},15000);d.client.publish(this.topic(id,row.topic),row.body,{qos:1,retain:false},e=>finish(e?'MQTT publish failed':null,started));}),p.faults.latencyMs||0);});}
 metrics(id){const d=this.devices.get(id);const p=this.plants.get(id);return publicMetrics(d?.metrics||initialMetrics(this.store.loadMetrics(id)),{connected:!!d?.client?.connected,paused:!!p?.replay.paused,telemetrySeconds:this.telemetrySeconds,clientId:this.deviceConfig[id]?.MQTT_CLIENT_ID||`${this.env.MQTT_CLIENT_ID||'vpp-scada-lab'}-${id}`,telemetryTopic:this.topic(id,'telemetry'),...this.store.queueStats(id)});}
 gateway(){return {connected:!!this.gatewayClient?.connected,clientId:this.env.MQTT_CLIENT_ID||'vpp-scada-lab',lastError:this.gatewayError,rssBytes:process.memoryUsage().rss,uptimeSeconds:process.uptime(),scope:'shared Node process; not per-RTU hardware'};}
 async stop(){this.running=false;clearInterval(this.pumpTimer);clearInterval(this.batchTimer);const clients=[];for(const d of this.devices.values()){if(d.inflight){clearTimeout(d.inflight.delay);clearTimeout(d.inflight.timeout);d.inflight=null;}d.metrics.telemetryPending=0;this.guard(d,()=>this.save(d));if(d.client)clients.push([d.client,this.topic(d.id,'status'),d.id]);}if(this.gatewayClient)clients.push([this.gatewayClient,`${this.prefix}/gateway/status`,null]);await Promise.all(clients.map(([c,topic,id])=>new Promise(resolve=>{const timer=setTimeout(()=>{c.end(true);resolve();},1500);const end=()=>c.end(false,()=>{clearTimeout(timer);resolve();});if(c.connected)c.publish(topic,JSON.stringify({online:false,...id?{rtuId:id}:{}}),{qos:1,retain:true},end);else{c.end(true);clearTimeout(timer);resolve();}})));}
}
