// Declarative real-browser recorder. No final claims are generated by this tool.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync,spawn}=require('node:child_process');
const modules=process.env.RUNTIME_NODE_MODULES||'/Users/charleskoh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(path.join(modules,'playwright'));
const ffmpeg=process.env.FFMPEG||'/Users/charleskoh/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/lib/python3.12/site-packages/imageio_ffmpeg/binaries/ffmpeg-macos-aarch64-v7.1';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
let activeBrowser;const executionStarted=Date.now();
const srt=t=>new Date(Math.round(t*1000)).toISOString().slice(11,23).replace('.',',');
function duration(p){let r;try{execFileSync(ffmpeg,['-i',p],{stdio:'pipe'});}catch(e){r=e.stderr.toString();}const m=r?.match(/Duration: (\d+):(\d+):([\d.]+)/);if(!m)throw Error('Cannot inspect media duration');return +m[1]*3600 + +m[2]*60 + +m[3];}
(async()=>{
 const config=JSON.parse(fs.readFileSync(process.argv[2]));const rehearsal=process.argv.includes('--rehearsal');
 const run=JSON.parse(fs.readFileSync('docs/operations/run.json'));
 if(!rehearsal && (Date.now()<Date.parse(run.freezeAt)||Date.now()>Date.parse(run.deadlineAt)))throw Error('Final recording must occur within frozen final 30 minutes');
 if(!rehearsal && config.preparationTemplate)throw Error('Populate the template and clear preparationTemplate before final capture');
 if(!config.scenes?.length)throw Error('Scenes required');
 const manifest=JSON.parse(fs.readFileSync(config.releaseManifest));
 if(!rehearsal && (!config.approvedReleaseCommit || config.approvedReleaseCommit!==manifest.source.commit || !/(?:^|@)sha256:[a-f0-9]{64}$/.test(config.approvedImageDigest||'')))throw Error('Explicit verified release commit and image digest required');
 if(config.rehearsalName&&!/^[a-z0-9-]+$/.test(config.rehearsalName))throw Error('Invalid rehearsal name');
 const out=path.resolve(rehearsal?'artifacts/media-preparation/'+(config.rehearsalName||'rehearsal'):config.outputDir||'artifacts/video');
 if(fs.existsSync(path.join(out,'GRID-VPP-demo-ko.mp4')))throw Error('Refusing to overwrite existing video');
 fs.mkdirSync(out,{recursive:true});const audioDir=path.join(out,'source');fs.mkdirSync(audioDir,{recursive:true});
 // Voice is generated first. Each scene gets enough time for both its real action and voice.
 for(let i=0;i<config.scenes.length;i++){const sc=config.scenes[i];sc.voice=path.join(audioDir,`voice-${i}.aiff`);sc.cues=[];let offset=0;const inputs=[];const parts=sc.narration.match(/[^.!?。]+[.!?。]?/g)||[sc.narration];
  for(let j=0;j<parts.length;j++){const file=path.join(audioDir,`voice-${i}-${j}.aiff`);execFileSync('say',['-v','Yuna','-r',String(config.speechRate||170),'-o',file,parts[j].trim()]);const seconds=duration(file);sc.cues.push({start:offset,end:offset+seconds,text:parts[j].trim()});offset+=seconds;inputs.push('-i',file);}
  execFileSync(ffmpeg,['-y',...inputs,'-filter_complex',parts.map((_,j)=>`[${j}:a]`).join('')+`concat=n=${parts.length}:v=0:a=1[a]`,'-map','[a]',sc.voice],{stdio:'pipe'});sc.duration=Math.max(sc.seconds||0,duration(sc.voice)+1.5);
 }
 const browser=activeBrowser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
 // Authenticate before opening the recorded context; storageState avoids filming credentials.
 const setup=await browser.newContext();let state;
 if(config.tokenFile){const token=fs.readFileSync(config.tokenFile,'utf8').trim();await setup.addInitScript(token=>sessionStorage.setItem('grid-token',token),token);}
 const probe=await setup.newPage();await probe.goto(config.baseUrl);state=await setup.storageState();await setup.close();
 const context=await browser.newContext({viewport:{width:1920,height:1080},storageState:state,recordVideo:{dir:audioDir,size:{width:1920,height:1080}}});
 if(config.tokenFile){const token=fs.readFileSync(config.tokenFile,'utf8').trim();await context.addInitScript(token=>sessionStorage.setItem('grid-token',token),token);}
 await context.addInitScript(rehearsal=>addEventListener('DOMContentLoaded',()=>{if(rehearsal){const b=document.createElement('div');b.textContent='제작 리허설 · 로컬 가상 데이터 · 최종 결과물 아님';b.style.cssText='position:fixed;top:6px;left:35%;padding:8px 18px;background:#102319ee;color:#c5f16c;font:20px sans-serif;z-index:999997;pointer-events:none';document.body.append(b);}const p=document.createElement('div');p.style.cssText='position:fixed;left:20px;top:20px;width:22px;height:22px;border:3px solid white;border-radius:50%;background:#c5f16c88;z-index:999999;pointer-events:none;box-shadow:0 0 0 6px #0005';document.body.append(p);addEventListener('mousemove',e=>{p.style.left=e.clientX-11+'px';p.style.top=e.clientY-11+'px'});addEventListener('mousedown',()=>p.style.boxShadow='0 0 0 18px #c5f16c99');addEventListener('mouseup',()=>setTimeout(()=>p.style.boxShadow='0 0 0 6px #0005',400));}),rehearsal);
 const page=await context.newPage();const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));page.setDefaultTimeout(10000);await page.goto(config.baseUrl);await page.getByText('실시간 연결',{exact:true}).waitFor();
 const started=Date.now();const scenes=[],interactions=[],downloads=[];
 for(let i=0;i<config.scenes.length;i++){
  const sc=config.scenes[i],start=(Date.now()-started)/1000;console.log(JSON.stringify({recordingScene:i+1,title:sc.title}));
  for(const a of sc.actions||[]){const el=a.selector?page.locator(a.selector):a.label?page.getByLabel(a.label,{exact:a.exact===true}):a.role?page.getByRole(a.role,{name:a.name,exact:a.exact!==false}):a.text?page.getByText(a.text,{exact:a.exact!==false}):null;
   if(a.type==='capture'){if(!/^[a-z0-9-]+$/.test(a.name))throw Error('Invalid capture name');await page.screenshot({path:path.join(audioDir,`${a.name}.png`)});}
   else if(a.type==='dispatch'){
    const report=path.join(audioDir,`vpp-command-${i}.json`);const env={...process.env,MQTT_URL:config.mqtt.url,MQTT_PREFIX:config.mqtt.prefix||'vpp',MQTT_USERNAME:config.mqtt.username||'',MQTT_PASSWORD:config.mqtt.passwordFile?fs.readFileSync(config.mqtt.passwordFile,'utf8').trim():'',RTU_ID:a.rtuId==='selected'?await page.locator('.plant-selector select').inputValue():a.rtuId,TARGET_KW:String(a.targetKw),COMMAND_TIMEOUT_SECONDS:String(a.timeoutSeconds||20),VPP_REPORT_FILE:report};
    await new Promise((resolve,reject)=>{const child=spawn(process.execPath,['scripts/vpp-client.js','--dispatch'],{env,stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const timer=setTimeout(()=>{child.kill('SIGTERM');reject(Error('Demo dispatch exceeded bounded timeout'));},90000);child.on('error',e=>{clearTimeout(timer);reject(e)});child.on('exit',code=>{clearTimeout(timer);fs.writeFileSync(path.join(audioDir,`vpp-command-${i}.log`),log);code===0?resolve():reject(Error('Observed VPP dispatch did not complete; preserve evidence and correct narration'));});});
    const result=JSON.parse(fs.readFileSync(report));if(result.lastStatus!=='completed'||result.actualKw===null)throw Error('Missing observed completed VPP result');
   }else if(a.type==='drag'){let from=a.from,to=a.to;if(el){await el.evaluate(n=>n.scrollIntoView({block:'center'}));const b=await el.boundingBox();from=[b.x+b.width*(a.from?.[0]||.4),b.y+b.height*(a.from?.[1]||.5)];to=[b.x+b.width*(a.to?.[0]||.65),b.y+b.height*(a.to?.[1]||.55)];}await page.mouse.move(from[0],from[1],{steps:35});await page.mouse.down();await page.mouse.move(to[0],to[1],{steps:50});await page.mouse.up();}
   else if(a.type==='press')await page.keyboard.press(a.key);
   else if(a.type==='wait')await page.waitForTimeout(a.ms||1000);
   else if(a.type==='scroll')await page.mouse.wheel(a.x||0,a.y||500);
   else if(a.type==='assert')await el.waitFor({state:'visible'});
   else if(a.type==='move')await page.mouse.move(a.x,a.y,{steps:40});
   else {await el.scrollIntoViewIfNeeded();const b=await el.boundingBox();if(!b)throw Error('Target not visible');await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:35});
    if(a.type==='download'){
     if(a.validate!=='command-states'||!/^[a-z0-9-]+\.json$/.test(a.file||''))throw Error('Unsupported or unsafe download request');
     const selected=page.locator('.plant-selector select');const selectedId=a.rtuId&&a.rtuId!=='selected'?a.rtuId:await selected.count()?await selected.inputValue():(await page.locator('.row-selected small.mono').textContent()).trim();
     const [download]=await Promise.all([page.waitForEvent('download',{timeout:10000}),(async()=>{await page.mouse.down();interactions.push({kind:'click',at:(Date.now()-started)/1000,x:b.x+b.width/2,y:b.y+b.height/2});await page.waitForTimeout(180);await page.mouse.up();})()]);
     if(await download.failure())throw Error('Command state browser download failed');const temporary=await download.path();const bytes=fs.readFileSync(temporary);const secrets=[config.tokenFile,config.mqtt?.passwordFile].filter(Boolean).map(p=>fs.readFileSync(p,'utf8').trim());
     const checked=require('./validate-command-download.cjs')(bytes,selectedId,secrets);const output=path.join(audioDir,a.file);if(fs.existsSync(output))throw Error('Refusing to overwrite downloaded evidence');await download.saveAs(output);downloads.push({...checked,file:path.relative(out,output),sha256:hash(output),at:(Date.now()-started)/1000});
    }
    else if(a.type==='click'){await page.mouse.down();interactions.push({kind:'click',at:(Date.now()-started)/1000,x:b.x+b.width/2,y:b.y+b.height/2});await page.waitForTimeout(180);await page.mouse.up();}
    else if(a.type==='range'){await el.focus();await el.press('Home');const min=Number(await el.getAttribute('min')||0),step=Number(await el.getAttribute('step')||1);for(let n=0;n<Math.round((a.value-min)/step);n++)await el.press('ArrowRight');}
    else if(a.type==='fill')await el.fill(String(a.value));else if(a.type==='select')await el.selectOption(a.option||String(a.value));else if(a.type==='upload')await el.setInputFiles(a.file);else if(a.type==='focus')await el.evaluate(n=>n.scrollIntoView({block:'center'}));else throw Error('Unsupported action '+a.type);
   }
  }

  const used=(Date.now()-started)/1000-start;await page.waitForTimeout(Math.max(0,(sc.duration-used)*1000));
  await page.screenshot({path:path.join(audioDir,`scene-${i+1}.png`)});
  scenes.push({...sc,start,end:(Date.now()-started)/1000});
 }
 const raw=await page.video().path();await context.close();await browser.close();if(pageErrors.length)throw Error('Browser error occurred during capture; inspect live UI before finalizing');
 // Browser recording includes load time. Match audio to first scene using duration difference.
 const rawDuration=duration(raw),sceneDuration=scenes.at(-1).end,lead=Math.max(0,rawDuration-sceneDuration);
 const args=['-y','-i',raw];for(const sc of scenes)args.push('-i',sc.voice);
 const audio=scenes.map((sc,i)=>`[${i+1}:a]adelay=${Math.round((sc.start+lead)*1000)}:all=1[a${i}]`).join(';')+';'+scenes.map((_,i)=>`[a${i}]`).join('')+`amix=inputs=${scenes.length}:normalize=0:duration=longest[a]`;
 // One continuous, gradual zoom per requested scene, never fake UI content.
 const zooms=scenes.filter(sc=>sc.zoom).map(sc=>{const t0=(sc.start+lead+1)*30,t1=(sc.end+lead-1)*30,amount=Math.min(.25,Math.max(0,(sc.zoom.scale||1.12)-1));return `${amount}*max(0,min(1,min((in-${t0})/30,(${t1}-in)/30)))`;});
 const z=zooms.length?'1+'+zooms.join('+'):'1';
 const subtitles=[];for(const sc of scenes){for(const cue of sc.cues){const lines=[];let line='';for(const word of cue.text.split(/\s+/)){if(line.length+word.length>36){lines.push(line);line='';}line+=(line?' ':'')+word;}if(line)lines.push(line);subtitles.push(`${subtitles.length+1}\n${srt(sc.start+lead+cue.start)} --> ${srt(sc.start+lead+cue.end)}\n${lines.join('\n')}\n`);}}
 fs.writeFileSync(path.join(out,'GRID-VPP-demo-ko.srt'),subtitles.join('\n'));
 const video=`fps=30,zoompan=z='${z}':x='iw/2-iw/zoom/2':y='ih/2-ih/zoom/2':d=1:s=1920x1080:fps=30,subtitles=filename='${path.join(out,'GRID-VPP-demo-ko.srt').replaceAll("'","\\'")}':force_style='FontName=Apple SD Gothic Neo,FontSize=12,PrimaryColour=&H00FFFFFF,OutlineColour=&H00101B12,BorderStyle=3,Outline=2,MarginV=12'`;
 const encoded=path.join(audioDir,'encoded.mp4');const mp4=path.join(out,'GRID-VPP-demo-ko.mp4');
 args.push('-filter_complex',audio,'-map','0:v','-map','[a]','-vf',video,'-c:v','libx264','-preset','veryfast','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','160k','-t',String(rawDuration),'-movflags','+faststart',encoded);execFileSync(ffmpeg,args,{stdio:'pipe'});
 execFileSync(ffmpeg,['-y','-i',encoded,'-i',path.join(out,'GRID-VPP-demo-ko.srt'),'-map','0:v','-map','0:a','-map','1:0','-c:v','copy','-c:a','copy','-c:s','mov_text','-metadata:s:s:0','language=kor','-disposition:s:0','0','-movflags','+faststart',mp4],{stdio:'pipe'});
 fs.writeFileSync(path.join(out,'narration-ko.md'),scenes.map((sc,i)=>`## ${i+1}. ${sc.title}\n\n${sc.narration}`).join('\n\n'));
 fs.writeFileSync(path.join(out,'scenes.json'),JSON.stringify({rehearsal,lead,scenes,interactions,downloads},null,2));
 execFileSync(ffmpeg,['-v','error','-i',mp4,'-f','null','-'],{stdio:'pipe'});
 const audioProbe=require('node:child_process').spawnSync(ffmpeg,['-hide_banner','-i',mp4,'-vn','-af','volumedetect','-f','null','-'],{encoding:'utf8'});const audioMeanDb=Number(audioProbe.stderr.match(/mean_volume: ([\d.-]+) dB/)?.[1]);if(audioProbe.status!==0||!Number.isFinite(audioMeanDb))throw Error('Missing or silent audio stream');
 const frames=[];for(const [i,t] of [lead+2,rawDuration/2,rawDuration-2,...interactions.slice(0,2).map(e=>lead+e.at+.08),...scenes.filter(s=>s.zoom).map(s=>lead+s.start+3)].entries()){const p=path.join(out,`frame-${i+1}.png`);execFileSync(ffmpeg,['-y','-ss',String(t),'-i',mp4,'-frames:v','1',p],{stdio:'pipe'});frames.push(p);}
 fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify({rehearsal,createdAt:new Date().toISOString(),productionSeconds:(Date.now()-executionStarted)/1000,releaseCommit:manifest.source.commit,imageDigest:config.approvedImageDigest||null,manifestSha256:hash(config.releaseManifest),videoSha256:hash(mp4),fullDecode:true,audioMeanDb,pageErrors,downloads,duration:duration(mp4),dimensions:'1920x1080',codecs:'H264/AAC',frames,visualReview:'pending',claimsReview:'pending'},null,2));
 console.log(JSON.stringify({output:out,rehearsal,fullDecode:true,visualReview:'pending'}));
})().catch(async e=>{console.error(e.message);await activeBrowser?.close().catch(()=>{});process.exitCode=1});
